title: Prajeet Basu
# theme: jekyll-theme-dinky
plugins:
  - jekyll-remote-theme # Add the plugin

# remote_theme: daviddarnes/alembic@main # Replace with the theme repo
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"

locale: en-US
title: "So Simple"
description: "A simple Jekyll theme for words and pictures."

