# theme: jekyll-theme-dinky
plugins:
  - jekyll-remote-theme # Add the plugin

# remote_theme: daviddarnes/alembic@main # Replace with the theme repo
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"

locale: en-US
title: "Prajeet Basu"
description: " 'A man's dreams will never end' "
baseurl: "/prajeetbasu"
url: "https://PrajeetCoding.github.io"
logo: "/images/chicago.jpg"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    

skin: "/assets/css/skins/dark.css"

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

copyright: "This site is made by Prajeet Basu."

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

